### PR TITLE
[Card Grants] Properly handle overwithdrawal error

### LINKED ISSUE #10363: Overwithdrawaling from card grant displays error page instead of banner
### Describe your goals

Withdrawal more money than was on a card grant

### Describe the bug

It redirected to a generic error page instead of showing a warning banner

Image

### PR DESCRIPTION
**Pull request by Luke-Oldenburg**
Closes #10363
Screenshot From 2025-05-08 15-09-58

### CODE REVIEW

File: app/controllers/card_grants_controller.rb [hunk 1]
```diff
@@ -136,6 +136,11 @@ def withdraw
     @card_grant.withdraw!(amount_cents: Monetize.parse(params[:amount]).cents, withdrawn_by: current_user)
 
     redirect_to @card_grant, flash: { success: "Successfully withdrew from grant." }
+
+  rescue => e
+    Rails.error.report(e)
```
Comment (sampoder) [inline app/controllers/card_grants_controller.rb]: I don't think we should be reporting `ArgumentError`s that we're raising ourselves

Comment (sampoder) [reply app/controllers/card_grants_controller.rb]: We should be reporting other errors though - sorry should have been clearer there

Comment (Luke-Oldenburg) [reply app/controllers/card_grants_controller.rb]: Oh lol. How can I detect if it is an error we are raising ourselves?

Comment (sampoder) [reply app/controllers/card_grants_controller.rb]: I think you can do something like `unless e.is_a?(ArgumentError)` (I think - test this)

Comment (Luke-Oldenburg) [reply app/controllers/card_grants_controller.rb]: Tested it. I didn't really notice it logging anything different either way. I tried searching in the terminal for the string that is flashed in the UI.

Comment (Luke-Oldenburg) [reply app/controllers/card_grants_controller.rb]: It didn't break anything though.

**Comment by sampoder** [comment]
Error reporting happens in production
