### PR TITLE
[Card Grants] Overview Page

### LINKED ISSUE #10547: ActionView::Template::Error happened in: CardGrantsController#new
### [Incident: #1885] ActionView::Template::Error happened in: CardGrantsController#new

**Message**

```
undefined local variable or method 'card_grant' for an instance of #<Class:0x00007dbf828985e0>
```

**Backtrace (up to last 10 lines)**

```
app/views/card_grants/_create_form.html.erb:1
actionview (7.2.2.1) lib/action_view/base.rb:281:in 'Kernel#public_send'
actionview (7.2.2.1) lib/action_view/base.rb:281:in 'ActionView::Base#_run'
actionview (7.2.2.1) lib/action_view/template.rb:285:in 'block in ActionView::Template#render'
appsignal (4.5.4) lib/appsignal/hooks/active_support_notifications.rb:19:in 'block in ActiveSupport::Notifications.instrument'
activesupport (7.2.2.1) lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
appsignal (4.5.4) lib/appsignal/hooks/active_support_notifications.rb:18:in 'ActiveSupport::Notifications.instrument'
actionview (7.2.2.1) lib/action_view/template.rb:584:in 'ActionView::Template#instrument_render_template'
actionview (7.2.2.1) lib/action_view/template.rb:273:in 'ActionView::Template#render'
actionview (7.2.2.1) lib/action_view/renderer/partial_renderer.rb:252:in 'block in ActionView::PartialRenderer#render_partial_template'
```

View on AppSignal: https://appsignal.com/hack-club/sites/6596247683eb67648f30f807/exceptions/incidents/1885?id=last

### PR DESCRIPTION
**Pull request by Luke-Oldenburg**
Screenshot From 2025-09-22 17-45-27
Filtering and searching will come in a subsequent PR but it would be nice to have this page up now for organizers.

### CODE REVIEW

File: app/controllers/events_controller.rb [hunk 1]
```diff
@@ -459,6 +459,22 @@ def card_overview
     @all_unique_cardholders = @event.stripe_cards.on_main_ledger.map(&:stripe_cardholder).uniq
   end
 
+  def card_grants_overview
+    cookies[:card_overview_view] = params[:view] if params[:view]
+    @view = cookies[:card_overview_view] || "grid"
```
Comment (garyhtou) [inline app/controllers/events_controller.rb]: It looks like this is the same code as `cards_overview` let's move this to a `before_action`

File: app/controllers/events_controller.rb [hunk 2]
```diff
@@ -459,6 +459,22 @@ def card_overview
...
+
+    page = (params[:page] || 1).to_i
+    per_page = (params[:per] || 20).to_i
+
+    authorize @event
+
+    @all_stripe_cards = @event.stripe_cards.where.associated(:card_grant)
+    @paginated_stripe_cards = Kaminari.paginate_array(@all_stripe_cards).page(page).per(per_page)
+
+    @hcb_codes = HcbCode.where(id: @all_stripe_cards.flat_map(&:hcb_codes))
```
Comment (garyhtou) [inline app/controllers/events_controller.rb]: This creates a N+1, instead, let's flat_map for the `hcb_code` strings, then do:

```suggestion
    @hcb_codes = HcbCode.where(hcb_code: @all_stripe_cards.flat_map(&:all_hcb_codes))
```

File: app/controllers/events_controller.rb [hunk 3]
```diff
@@ -459,6 +459,22 @@ def card_overview
...
+    cookies[:card_overview_view] = params[:view] if params[:view]
+    @view = cookies[:card_overview_view] || "grid"
+
+    page = (params[:page] || 1).to_i
+    per_page = (params[:per] || 20).to_i
+
+    authorize @event
+
+    @all_stripe_cards = @event.stripe_cards.where.associated(:card_grant)
+    @paginated_stripe_cards = Kaminari.paginate_array(@all_stripe_cards).page(page).per(per_page)
```
Comment (garyhtou) [inline app/controllers/events_controller.rb]:
```suggestion
    @paginated_stripe_cards = @all_stripe_cards.page(page).per(per_page)
```

File: app/controllers/events_controller.rb [hunk 4]
```diff
@@ -459,6 +459,22 @@ def card_overview
...
+
+    @hcb_codes = HcbCode.where(id: @all_stripe_cards.flat_map(&:hcb_codes))
+    @paginated_hcb_codes = Kaminari.paginate_array(@hcb_codes).page(params[:page]).per(25)
```
Comment (garyhtou) [inline app/controllers/events_controller.rb]:
```suggestion
    @paginated_hcb_codes = @hcb_codes.page(params[:page]).per(25)
```

File: app/views/events/_nav.html.erb [hunk 5]
```diff
@@ -84,6 +84,11 @@
       tooltip: "Manage payroll",
       icon: "person-badge",
       selected: local_assigns[:selected] == :payroll if Flipper.enabled?(:payroll_2025_02_13, @event) %>
+    <%= dock_item "Card grants",
```
Comment (garyhtou) [inline app/views/events/_nav.html.erb]: Add this to the mobile nav too

File: app/views/events/card_grants_overview.html.erb [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+<% if current_user.try(:full_name).try(:blank?) %>
+
+  <h1 class="heading">
+    <span class="flex items-center">
+      Card grants
+    </span>
+  </h1>
+
+  <%= render "cards/name_required" %>
+<% else %>
```
Comment (garyhtou) [inline app/views/events/card_grants_overview.html.erb]: We can drop this since you aren't create your own cards here

File: app/views/events/card_grants_overview.html.erb [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+      <%= badge_for @event.card_grants.active.count, class: "bg-muted" %>
+    </span>
+
+    <%= pop_icon_to @view == "list" ? "grid" : "list",
+                    "?view=#{@view == 'list' ? 'grid' : 'list'}#{"&q=#{@q}" if @q}#{"&status=#{@status}" if @status}" %>
+    <% if organizer_signed_in?(as: :member) %>
+      <%= link_to new_event_card_grant_path(@event), class: "btn bg-success", data: { behavior: "modal_trigger", modal: "create_card_grant" } do %>
+        <%= inline_icon "card-add" %>
+        Send a grant
+      <% end %>
```
Comment (garyhtou) [inline app/views/events/card_grants_overview.html.erb]: Disable if not a manager

File: app/views/events/card_grants_overview.html.erb [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+      <% else %>
+        <%= blankslate "This organization doesn't have any card grants" %>
+      <% end %>
+    <% end %>
+  <% end %>
+
+  <div class="table-container">
+  <table>
+    <tbody data-behavior="transactions">
+      <% @hcb_codes.order(created_at: :desc).each do |hcb_code| %>
```
Comment (garyhtou) [inline app/views/events/card_grants_overview.html.erb]: Move this before pagination

File: app/views/events/card_grants_overview.html.erb [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+    </article>
+
+    <% if @paginated_stripe_cards.blank? %>
+      <% if organizer_signed_in? %>
+        <%= blankslate "You don't have any card grants yet." %>
+      <% else %>
+        <%= blankslate "This organization doesn't have any card grants" %>
+      <% end %>
+    <% end %>
+  <% end %>
```
Comment (garyhtou) [inline app/views/events/card_grants_overview.html.erb]: You may wanna add:
```erb
<%= paginate @paginated_stripe_cards %>
```

**Review by garyhtou — COMMENTED** [review]
I like the direction of this. Looks good— just add a loading indicator for the turbo frames

File: app/controllers/card_grants_controller.rb [hunk 10]
```diff
@@ -6,8 +6,39 @@ class CardGrantsController < ApplicationController
...
 
-  before_action :set_event, only: %i[new create]
-  before_action :set_card_grant, except: %i[new create]
+  before_action :set_event, only: [:new, :create, :index, :card_index, :transaction_index]
+  before_action :set_card_grant, except: [:new, :create, :index, :card_index, :transaction_index]
+
+  def index
+    authorize @event, :card_grant_overview?
+
+    render "events/card_grants/overview"
```
Comment (sampoder) [inline app/controllers/card_grants_controller.rb]: For consistency can this just be `index.html.erb`?

File: app/models/stripe_card.rb [hunk 11]
```diff
@@ -350,6 +350,10 @@ def canonical_transactions
     @canonical_transactions ||= CanonicalTransaction.stripe_transaction.where("raw_stripe_transactions.stripe_transaction->>'card' = ?", stripe_id)
   end
 
+  def all_hcb_codes
+    canonical_transaction_hcb_codes + canonical_pending_transaction_hcb_codes
+  end
+
```
Comment (sampoder) [inline app/models/stripe_card.rb:356]: This and `hcb_codes` are kind of confusing? Should `hcb_codes` be `local_hcb_codes` and call this method?

File: app/views/card_grants/show.html.erb [hunk 12]
```diff
@@ -65,7 +65,7 @@
 
 <hr>
 
-<% unless @card_grant.user == current_user && @card_grant.pending_invite? %>
+<% unless @card_grant.pending_invite? %>
   <%= render partial: "transactions", locals: { hcb_codes: @hcb_codes } %>
 <% end %>
```
Comment (sampoder) [inline app/views/card_grants/show.html.erb:71]: Hmm - why the change?

File: app/models/stripe_card.rb (hunk 11 above)
Comment (Luke-Oldenburg) [reply app/models/stripe_card.rb:356]: I'm hesitant to rename the other function because I might not find all usages and I don't totally understand the usage of an instance variable in it. It is a good move to call this from there though.

File: app/views/card_grants/index.html.erb [hunk 13]
```diff
@@ -0,0 +1,26 @@
...
+  <% end %>
+</h1>
+
+<%= turbo_frame_tag :card_grant_card_overview, src: event_card_grant_card_overview_path(@event), loading: :eager do %>
+  <p>Loading card grants</p>
+<% end %>
+
+<%= turbo_frame_tag :card_grant_transaction_overview, src: event_card_grant_transaction_overview_path(@event), loading: :eager do %>
+  <p>Loading transactions</p>
+<% end %>
```
Comment (polypixeldev) [inline app/views/card_grants/index.html.erb:42]: nit: loading state could look better but it's fine for now image

File: app/views/card_grants/card_index.html.erb [hunk 14]
```diff
@@ -0,0 +1,46 @@
...
+              <%= card_grant.purpose.presence || Disbursement.find_by(id: card_grant.disbursement_id).local_hcb_code.memo %>
+            </td>
+            <td>
+              <%= render_money card_grant.amount_cents %>
+            </td>
+            <td class="text-right">
+              <%= render_money card_grant.balance %>
+            </td>
+            <td>
+              <%= render "events/card_grant_actions", card_grant: %>
```
Comment (polypixeldev) [inline app/views/card_grants/card_index.html.erb]: nit: I think there should still be a link to the actual card grant page in the table row and not hidden behind the actions menu, like how it currently is on the transfers page

**Review by polypixeldev — COMMENTED** [review]
awesome! just a few things:
- page looks off with no grants - add blankslates to both frames image

File: app/controllers/card_grants_controller.rb [hunk 15]
```diff
@@ -6,8 +6,33 @@ class CardGrantsController < ApplicationController
...
+    authorize @event, :card_grant_overview?
+  end
+
+  def card_index
+    authorize @event, :card_grant_overview?
+
+    card_grants_page = (params[:page] || 1).to_i
+    card_grants_per_page = (params[:per] || 20).to_i
+
+    @card_grants = @event.card_grants.order(created_at: :desc)
```
Comment (garyhtou) [inline app/controllers/card_grants_controller.rb]:
```suggestion
    @card_grants = @event.card_grants.includes(:disbursement).order(created_at: :desc)
```

File: app/models/stripe_card.rb (hunk 11 above)
Comment (garyhtou) [reply app/models/stripe_card.rb:356]: here are potential usages. let's come back and fix this in another PR

image

**Review by garyhtou — APPROVED** [review]
nice! we'll merge and come back to fix up performance for the transactions turboframe
