### PR TITLE
[Google Workspace] Create the revocation feature

### LINKED ISSUE #9500: [Google Workspace] Audit for revocation
Once a month, audit all domains on Google Workspace for the following:
- Incorrect/missing DNS
- Domains with no longer for the past 6 months

Domains created within the past 3 months are safe.

When a domain is flagged, they've given 2 weeks to resolve/bring their domain back to compliance. This could mean:
- Setting up/fixing their DNS
- Signing into their Google Workspace account
When they're back to compliance, delete their `GSuite::Revocation` record and send them an email.

Then, after the two weeks are over, HCB will put the domains into a `pending_deletion` status. Where operations will then manually review each domain and click the delete button.

During the 2 week warning period, we should send a few emails:
1. At the start of the 2 weeks
2. At 1 week out from deletion
3. 1 day out from deletion ("Your Google Workspace will be deleted tomorrow")

The following email addresses should receive the warning emails:
- All managers in the HCB organization (if there are no managers, then all users in the HCB org)
- All Google users of the domain
- All backup email addresses of those Google users.

---

To do this, create a new model called

`GSuite::Revocation`
Columns:
- id
- invalid_dns (boolean)
- no_account_activity (boolean)
- references :g_suite
- aasm_state
  - warning
  - pending_revocation
  - revoked
- timestamps (created_at, updated_at)

```ruby
class GSuite
  has_one :revocation
end
```

### PR DESCRIPTION
**Pull request by rluodev**
## Summary of the problem

Closes https://github.com/hackclub/hcb/issues/9500

## Describe your changes

Screenshot 2025-05-08 at 5 14 47 PM

Screenshot 2025-05-08 at 5 15 07 PM

Screenshot 2025-05-08 at 5 15 46 PM

Screenshot 2025-05-08 at 5 16 45 PM

### CODE REVIEW

File: app/jobs/g_suite_job/initiate_revocations.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
+# frozen_string_literal: true
+
+module GSuiteJob
+  class InitiateRevocations < ApplicationJob
+    queue_as :low
+
+    def perform
+      GSuite.where(revocation: nil).find_each(batch_size: 100) do |g_suite|
```
Comment (garyhtou) [inline app/jobs/g_suite_job/initiate_revocations.rb]:
```suggestion
      GSuite.where(revocation_immunity: false).missing(:revocation).find_each(batch_size: 100) do |g_suite|
```

File: app/services/g_suite_service/create_revocation.rb
Comment (garyhtou) [inline app/services/g_suite_service/create_revocation.rb:1]: Let's try to avoid these services without complicated business logic. We can directly call create on the model from the job.

File: app/services/partners/google/g_suite/check_domain_for_inactivity.rb [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+            end
+            if inactive_accounts.count == res_count
+              return true
+            end
+
+            false
+          rescue => e
+            Rails.error.report(e)
+            throw :abort
+          end
```
Comment (garyhtou) [inline app/services/partners/google/g_suite/check_domain_for_inactivity.rb]: Let's move this to the model. It can be in a method called `accounts_inactive?`

File: app/models/g_suite_revocation.rb [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+#
+# Indexes
+#
+#  index_g_suite_revocations_on_g_suite_id  (g_suite_id)
+#
+# Foreign Keys
+#
+#  fk_rails_...  (g_suite_id => g_suites.id)
+#
+class GSuiteRevocation < ApplicationRecord
```
Comment (garyhtou) [inline app/models/g_suite_revocation.rb]: Add a datetime column called `scheduled_at`.

```ruby
after_initialize do
  self.scheduled_at = 2.weeks.from_now
end
```

Comment (garyhtou) [inline app/models/g_suite_revocation.rb]:
```suggestion
class GSuite
  class Revocation < ApplicationRecord
```

and then fixing the indent, and also add another `end` at the bottom of the file.

File: app/views/g_suite_mailer/notify_of_pending_revocation.erb [hunk 4]
```diff
@@ -0,0 +1,19 @@
+<p>Hi there,</p>
+
+<p>
+  Your Google Workspace access for <strong><%= @g_suite.domain %></strong> will be revoked on <%= (@g_suite_revocation.created_at + 2.weeks).strftime("%B %d, %Y") %> because <%= @g_suite_revocation.invalid_dns ? "you are missing required DNS records" : @g_suite_revocation.no_account_activity ? "all accounts on your domain have been inactive for the past six months" : @g_suite_revocation.other && @g_suite_revocation.other_reason.present? ? @g_suite_revocation.other_reason : "of an unknown reason" %>.
```
Comment (garyhtou) [inline app/views/g_suite_mailer/notify_of_pending_revocation.erb]: Move the reason logic into the model.

```ruby
def reason
  if invalid_dns?
    "asdflskdjf"
  elsif no_account_activity
    "sdfsdf"
  elsif other?
    other_reason
  else
    Rails.error. unexpected("GSuite: Unknown reason type")
  end
end
```

File: app/models/g_suite_revocation.rb [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+
+# == Schema Information
+#
+# Table name: g_suite_revocations
+#
+#  id                  :bigint           not null, primary key
+#  aasm_state          :string
+#  invalid_dns         :boolean          default(FALSE), not null
+#  no_account_activity :boolean          default(FALSE), not null
+#  other               :boolean          default(FALSE), not null
```
Comment (garyhtou) [inline app/models/g_suite_revocation.rb]: Replace this with an `enum` called `reason`.

```ruby
enum :reason, prefix: :because_of
```

```ruby
# usage
GSuite::Revocation.create!(reason: :invalid_dns)
GSuite::Revocation.create!(reason: :other, other_reason: "sldfjds")
revocation.because_of_invalid_dns?
```

File: app/models/g_suite_revocation.rb [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+#  other_reason        :text
```
Comment (garyhtou) [inline app/models/g_suite_revocation.rb]:
```ruby
validate :other_reason, presence: false, unless: :because_of_other?
```

File: app/views/g_suite_mailer/notify_of_pending_revocation.erb
Comment (garyhtou) [inline app/views/g_suite_mailer/notify_of_pending_revocation.erb:1]: Add a mailer preview for this.

File: db/schema.rb [hunk 7]
```diff
@@ -1062,7 +1075,7 @@
     t.text "unique_bank_identifier"
     t.date "date"
     t.bigint "raw_increase_transaction_id"
-    t.index ["duplicate_of_hashed_transaction_id"], name: "index_hashed_transactions_on_duplicate_of_hashed_transaction_id"
+    t.index ["duplicate_of_hashed_transaction_id"], name: "idx_on_duplicate_of_hashed_transaction_id_6a29e8a078"
```
Comment (garyhtou) [inline db/schema.rb]: Drop  unrelated changes

File: app/models/g_suite.rb [hunk 8]
```diff
@@ -115,6 +117,36 @@ def previously_verified?
...
+      false
+    rescue => e
+      Rails.error.report(e)
+      throw :abort
+    end
+  end
+
+  def immune_to_revocation?
+    self.revocation_immunity
+  end
```
Comment (garyhtou) [inline app/models/g_suite.rb]: If we think this looks nicer, then let's rename the column to `immune_to_revocation`.

File: app/jobs/g_suite_job/initiate_revocations.rb (hunk 1 above)
Comment (garyhtou) [reply app/jobs/g_suite_job/initiate_revocations.rb]: and drop the

```ruby
next if g_suite.immune_to_revocation?
```

File: app/mailers/g_suite_mailer.rb [hunk 9]
```diff
@@ -25,6 +25,11 @@ def notify_of_error_after_verified
     mail subject: "[Action Required] Your Google Workspace for #{@g_suite.domain} is missing critical DNS records"
   end
 
+  def notify_of_pending_revocation
+    set_g_suite_revocation
+    mail subject: "[Action Required] Your Google Workspace access for #{@g_suite.domain} will be revoked on #{@g_suite_revocation.scheduled_at.strftime("%B %d, %Y")}"
```
Comment (garyhtou) [inline app/mailers/g_suite_mailer.rb]:
```suggestion
    mail subject: "[Action Required] Your Google Workspace access for #{@g_suite.domain} may be revoked on #{@g_suite_revocation.scheduled_at.strftime("%B %d, %Y")}"
```

File: app/mailers/g_suite_mailer.rb [hunk 10]
```diff
@@ -25,6 +25,11 @@ def notify_of_error_after_verified
     mail subject: "[Action Required] Your Google Workspace for #{@g_suite.domain} is missing critical DNS records"
   end
 
+  def notify_of_pending_revocation
+    set_g_suite_revocation
```
Comment (garyhtou) [inline app/mailers/g_suite_mailer.rb]: Instead of calling `set_g_suite_revocation` here. Do

```ruby
before_action :set_g_suite_revocation, only: %i[notify_of_pending_revocation]
```

File: app/mailers/g_suite_mailer.rb [hunk 11]
```diff
@@ -40,6 +45,20 @@ def set_g_suite
     @g_suite = GSuite.find(params[:g_suite_id])
   end
 
+  def set_g_suite_revocation
+    @g_suite_revocation = GSuite::Revocation.find(params[:g_suite_revocation_id])
+    if @g_suite_revocation.because_of_invalid_dns?
```
Comment (garyhtou) [inline app/mailers/g_suite_mailer.rb]: We can just move this into the `notify_of_pending_revocation` method. Or, you can create a separate method such as:

```ruby
def revocation_reason
  # paste code here
end
```

File: app/models/g_suite.rb [hunk 12]
```diff
@@ -115,6 +117,36 @@ def previously_verified?
...
+        user_last_login = Partners::Google::GSuite::Shared::DirectoryClient.directory_client.get_user(user.id).last_login_time
+        if user_last_login.nil? || user_last_login < 6.months.ago
+          inactive_accounts << user
+        end
+      end
+      if inactive_accounts.count == res_count
+        return true
+      end
+
+      false
```
Comment (garyhtou) [inline app/models/g_suite.rb]:
```suggestion

      inactive_accounts.count == res_count
```

File: app/mailers/g_suite_mailer.rb [hunk 13]
```diff
@@ -25,6 +25,11 @@ def notify_of_error_after_verified
     mail subject: "[Action Required] Your Google Workspace for #{@g_suite.domain} is missing critical DNS records"
   end
 
+  def notify_of_pending_revocation
```
Comment (garyhtou) [inline app/mailers/g_suite_mailer.rb]:
```suggestion
  def revocation_warning
```

File: app/models/g_suite/revocation.rb [hunk 14]
```diff
@@ -0,0 +1,58 @@
...
+      # click "revoke" to delete the g_suite and all associated data/accounts
+
+      event :mark_pending_revocation do
+        transitions from: :warning, to: :pending_revocation
+      end
+    end
+
+    after_create_commit do
+      GSuiteMailer.with(g_suite_id: g_suite.id, g_suite_revocation_id: self.id).notify_of_pending_revocation.deliver_later
+    end
```
Comment (garyhtou) [inline app/models/g_suite/revocation.rb]:
```suggestion
    after_create_commit do
      return unless warning?

      GSuiteMailer.with(g_suite_id: g_suite.id, g_suite_revocation_id: self.id).revocation_warning.deliver_later
    end
```

File: db/migrate/20250211234055_create_g_suite_revocations.rb [hunk 15]
```diff
@@ -0,0 +1,13 @@
+class CreateGSuiteRevocations < ActiveRecord::Migration[7.2]
+  def change
+    create_table :g_suite_revocations do |t|
+      t.integer :reason, default: 0
```
Comment (garyhtou) [inline db/migrate/20250211234055_create_g_suite_revocations.rb]:
```suggestion
      t.integer :reason, default: 0, null: false
```

File: app/models/g_suite/revocation.rb [hunk 16]
```diff
@@ -0,0 +1,58 @@
...
+
+    after_initialize do
+      self.scheduled_at = 2.weeks.from_now
+    end
```
Comment (garyhtou) [inline app/models/g_suite/revocation.rb]:
```suggestion
    before_validation on: :create do
      self.scheduled_at = 2.weeks.from_now
    end
```

File: db/migrate/20250211234055_create_g_suite_revocations.rb [hunk 17]
```diff
@@ -0,0 +1,13 @@
...
+      t.text :other_reason
+      t.references :g_suite, null: false, foreign_key: true
+      t.string :aasm_state
+      t.datetime :scheduled_at
```
Comment (garyhtou) [inline db/migrate/20250211234055_create_g_suite_revocations.rb]:
```suggestion
      t.datetime :scheduled_at, null: false
```

File: db/migrate/20250212225113_add_g_suite_revocation_immunity.rb [hunk 18]
```diff
@@ -0,0 +1,5 @@
+class AddGSuiteRevocationImmunity < ActiveRecord::Migration[7.2]
+  def change
+    add_column :g_suites, :revocation_immunity, :boolean
```
Comment (garyhtou) [inline db/migrate/20250212225113_add_g_suite_revocation_immunity.rb]:
```suggestion
    add_column :g_suites, :revocation_immunity, :boolean, default: false, null: false
```

File: db/migrate/20250211234055_create_g_suite_revocations.rb
Comment (garyhtou) [inline db/migrate/20250211234055_create_g_suite_revocations.rb:1]: Tip: when messing with migrations, I suggest:
1. `bin/rails db:rollback STEP=1`, modify STEP to control the number of migrations you rollback. Or omit `STEP` for a default of 1
2. make your changes to the migration file
3. `bin/rails db:migrate`

File: app/jobs/g_suite_job/initiate_revocations.rb [hunk 19]
```diff
@@ -0,0 +1,21 @@
...
+module GSuiteJob
+  class InitiateRevocations < ApplicationJob
+    queue_as :low
+
+    def perform
+      GSuite.where(revocation_immunity: false)
+            .where("created_at < ?", 2.months.ago)
+            .missing(:revocation)
+            .find_each(batch_size: 100) do |g_suite|
+        if (g_suite.aasm_state == "verification_error")
```
Comment (garyhtou) [inline app/jobs/g_suite_job/initiate_revocations.rb]:
```suggestion
        if (g_suite.verification_error?)
```

File: app/models/g_suite/revocation.rb [hunk 20]
```diff
@@ -0,0 +1,72 @@
...
+
+      GSuiteMailer.with(g_suite_id: g_suite.id, g_suite_revocation_id: self.id).revocation_warning.deliver_later
+    end
+
+    before_validation on: :create do
+      self.scheduled_at = 2.weeks.from_now
+    end
+
+    after_destroy_commit do
+      unless destroyed_by_association?
```
Comment (garyhtou) [inline app/models/g_suite/revocation.rb]:
```suggestion
      unless destroyed_by_association.present?
```

File: app/views/admin/google_workspace_process.html.erb [hunk 21]
```diff
@@ -127,6 +127,27 @@
...
+<% else %>
+  <h3>Begin Revocation</h3>
+  <p>This will begin the revocation of the organization's Google Workspace access and send an email to the users on the organization notifying them of the upcoming revocation. The users will have 2 weeks to wrap up their activities before access is revoked.</p>
+  <%= form_with(model: [@g_suite, GSuite::Revocation.new], url: g_suite_revocations_path(@g_suite), method: :post, local: true) do |form| %>
+    <%= form.hidden_field :reason, value: "other" %>
+    <%= form.label :other_reason, "This Google Workspace is being revoked because..." %>
+    <%= form.text_field :other_reason placeholder: "you have broken the Google Workspace terms of service" %>
+    <%= form.submit "Begin Revocation", data: { confirm: "Are you sure?" }, class: "admin-bg-warning p1 rounded link-reset" %>
+  <% end %>
+<% end %>
```
Comment (garyhtou) [inline app/views/admin/google_workspace_process.html.erb]:
```suggestion
<% end %>

```

File: app/controllers/admin_controller.rb [hunk 22]
```diff
@@ -881,6 +884,9 @@ def google_workspaces
     relation = relation.search_domain(@q) if @q
     relation = relation.needs_ops_review if @needs_ops_review
     relation = relation.configuring if @configuring
+    relation = relation.verification_error if @verification_error
+    relation = relation.joins(:revocation) if @revocation_present
```
Comment (garyhtou) [inline app/controllers/admin_controller.rb]:
```suggestion
    relation = relation.joins(:revocation).where(revocation: {aasm_state: "pending"}) if @revocation_present
```

File: app/controllers/admin_controller.rb [hunk 23]
```diff
@@ -881,6 +884,9 @@ def google_workspaces
...
+    relation = relation.pending_deletion if @pending_deletion
```
Comment (garyhtou) [inline app/controllers/admin_controller.rb]:
```suggestion
    relation = relation.joins(:revocation).where(revocation: {aasm_state: "revoked"}) if @pending_deletion
```

File: app/controllers/g_suite_revocations_controller.rb [hunk 24]
```diff
@@ -0,0 +1,42 @@
...
+  end
+
+  def destroy
+    authorize @g_suite_revocation
+
+    if @g_suite_revocation.destroy
+      flash[:success] = "Revocation was successfully destroyed."
+      redirect_to g_suites_url
+    else
+      render :index, status: :unprocessable_entity
```
Comment (garyhtou) [inline app/controllers/g_suite_revocations_controller.rb]: redirect to the admin google workspace process page for this record and flash an error message

File: app/views/g_suite_mailer/revocation_warning.erb [hunk 25]
```diff
@@ -0,0 +1,19 @@
+<p>Hi there,</p>
+
+<p>
+  This is a notice that your Google Workspace access for <strong><%= @g_suite.domain %></strong> will be revoked <strong>in two weeks on <%= @g_suite_revocation.scheduled_at.strftime("%B %d, %Y") %></strong> because <%= @reason %>. If you do not take action to remedy the issue, your data and accounts will be irrecoverably deleted and you will no longer be able to access Google Workspace services through HCB until you reapply and are approved for access from the waitlist.
```
Comment (garyhtou) [inline app/views/g_suite_mailer/revocation_warning.erb]: use scheduled at

File: app/views/g_suite_mailer/revocation_warning.erb [hunk 26]
```diff
@@ -0,0 +1,19 @@
...
+</p>
+
+<p>
+  <% if @g_suite_revocation.because_of_invalid_dns? %>
+    If you would like to keep your Google Workspace access, follow the steps <%= link_to "here on your Google Workspace page", event_g_suite_overview_url(event_id: @g_suite.event.slug) %> to configure your DNS for Google Workspace. Once your domain is verified, you'll get an email that confirms the revocation has been cancelled.
+  <% elsif @g_suite_revocation.because_of_accounts_inactive? %>
+    If you would like to keep your Google Workspace access, please have at least one account on your domain log in to Google Workspace before <%= (@g_suite_revocation.created_at + 2.weeks).strftime("%B %d, %Y") %>. You'll get an email that confirms the revocation has been cancelled a day or two after we detect a login.
```
Comment (garyhtou) [inline app/views/g_suite_mailer/revocation_warning.erb]:
```suggestion
    If you would like to keep your Google Workspace access, please sign into your <%= @g_suite.domain %> account before <%= (@g_suite_revocation.created_at + 2.weeks).strftime("%B %d, %Y") %>. You'll get an email that confirms the revocation has been cancelled a day or two after we detect a login.
```

File: app/views/g_suite_mailer/revocation_warning.erb [hunk 27]
```diff
@@ -0,0 +1,19 @@
...
+  <% end %>
+  Please don't hesitate to reply with any questions.
+</p>
```
Comment (garyhtou) [inline app/views/g_suite_mailer/revocation_warning.erb]: Move this into a shared partial

File: app/jobs/g_suite_job/initiate_revocations.rb [hunk 28]
```diff
@@ -0,0 +1,21 @@
...
+          @g_suite.revocation = GSuite::Revocation.create!(g_suite: @g_suite, reason: :invalid_dns)
+        elsif g_suite.accounts_inactive?
+          @g_suite.revocation = GSuite::Revocation.create!(g_suite: @g_suite, reason: :accounts_inactive)
```
Comment (garyhtou) [inline app/jobs/g_suite_job/initiate_revocations.rb]:
```suggestion
          GSuite::Revocation.create!(g_suite: @g_suite, reason: :invalid_dns)
        elsif g_suite.accounts_inactive?
          GSuite::Revocation.create!(g_suite: @g_suite, reason: :accounts_inactive)
```

File: app/jobs/g_suite_job/close_remedied_revocations.rb [hunk 29]
```diff
@@ -0,0 +1,18 @@
...
+  class CloseRemediedRevocations < ApplicationJob
+    queue_as :low
+
+    def perform
+      GSuite::Revocation.find_each(batch_size: 100) do |revocation|
+        if revocation.because_of_invalid_dns? && revocation.g_suite.verified?
+          revocation.destroy!
+        elsif revocation.because_of_accounts_inactive? && !revocation.g_suite.accounts_inactive?
+          revocation.destroy!
+        end
```
Comment (garyhtou) [inline app/jobs/g_suite_job/close_remedied_revocations.rb]: Share logic for whether all checks pass or not

**Review by garyhtou — COMMENTED** [review]
notes from review call:

File: app/views/admin/google_workspace_process.html.erb [hunk 30]
```diff
@@ -1,5 +1,18 @@
 <h1>Process Google Workspace #<%= @g_suite.id %></h1>
-<p><small>Current Status: <%= @g_suite.aasm_state %></small></p>
+<p>
+  <small>
+    Current Status:
+    <% if @g_suite.revocation.present? %>
+      <% if @g_suite.revocation.pending? %>
+        Pending Revocation (scheduled for <%= format_datetime @g_suite.revocation.scheduled_at %>)
+      <% else %>
+        Revoked at <%= format_datetime @g_suite.revocation.revoked_at %>
```
Comment (garyhtou) [inline app/views/admin/google_workspace_process.html.erb]: Check the difference between revoked_at and scheduled_at

File: app/controllers/g_suites_controller.rb [hunk 31]
```diff
@@ -48,12 +48,18 @@ def update
...
-    else
-      render :index, status: :unprocessable_entity
+    ActiveRecord::Base.transaction do
+      Partners::Google::GSuite::DeleteDomain.new(domain: @g_suite.domain).run
+      if @g_suite.destroy
+        flash[:success] = "Google Workspace was successfully destroyed."
+        redirect_to google_workspaces_admin_index_path
+      else
+        raise ActiveRecord::Rollback, "Failed to destroy Google Workspace"
+      end
```
Comment (garyhtou) [inline app/controllers/g_suites_controller.rb]:
```suggestion
    Partners::Google::GSuite::DeleteDomain.new(domain: @g_suite.domain).run
    @g_suite.destroy!
    flash[:success] = "Google Workspace was successfully destroyed."
    redirect_to google_workspaces_admin_index_path
```

File: app/jobs/g_suite_job/initiate_revocations.rb [hunk 32]
```diff
@@ -0,0 +1,22 @@
...
+
+module GSuiteJob
+  class InitiateRevocations < ApplicationJob
+    queue_as :low
+
+    def perform
+      GSuite.where(immune_to_revocation: false)
+            .where("g_suites.created_at < ?", 2.months.ago)
+            .left_joins(:revocation)
+            .where(g_suite_revocations: { id: nil })
```
Comment (garyhtou) [inline app/jobs/g_suite_job/initiate_revocations.rb]:
```suggestion
            .missing(:revocation)
```

File: app/mailers/g_suite_mailer.rb
Comment (garyhtou) [inline app/mailers/g_suite_mailer.rb:1]: Move this new code into a `g_suite/revocation_mailer.rb` and when you need to access GSuite, go through the revocation

```ruby
def set_g_suite_revocation
  @g_suite_revocation = GSuite::Revocation.find(params[:g_suite_revocation_id])
  @g_suite = @g_suite_revocation.g_suite
end

```

File: app/services/partners/google/g_suite/delete_groups_on_domain.rb [hunk 33]
```diff
@@ -0,0 +1,37 @@
...
+            puts "☣️ In production, we would currently be updating the GSuite on Google Admin ☣️"
+            return
+          end
+          begin
+            res = directory_client.list_groups(customer: gsuite_customer_id, domain: @domain)
+            res.groups.each do |group|
+              directory_client.delete_group(group.id)
+            end
+          rescue => e
+            puts "abcdef #{e}"
```
Comment (garyhtou) [inline app/services/partners/google/g_suite/delete_groups_on_domain.rb]:
```suggestion
```

File: app/services/partners/google/g_suite/delete_users_on_domain.rb [hunk 34]
```diff
@@ -0,0 +1,37 @@
...
+            puts "☣️ In production, we would currently be updating the GSuite on Google Admin ☣️"
+            return
+          end
+          begin
+            res = directory_client.list_users(customer: gsuite_customer_id, domain: @domain, max_results: 500)
+            res.users.each do |user|
+              directory_client.delete_user(user.id)
+            end
+          rescue => e
+            puts "abcdefg #{e}"
```
Comment (garyhtou) [inline app/services/partners/google/g_suite/delete_users_on_domain.rb]:
```suggestion
```

File: app/views/events/g_suite_overview.html.erb [hunk 35]
```diff
@@ -27,257 +27,279 @@
...
-        <p class="mt0">We’ll email you as soon as it’s ready.</p>
-      </section>
-    <% end %>
-    <% unless @g_suite.creating? %>
-      <% unless @g_suite.verified? || @g_suite.previously_verified? %>
-        <section class="card center mt3 mb3 bg-success white pt3">
-          <%= inline_icon "rep", size: 32 %>
-          <h3 class="mt0 mb0">Your registration was approved!</h3>
-          <p class="mt0">It’s time to set up your servers.</p>
+    <% if !(@g_suite.revocation.present? && @g_suite.revocation.revoked?) %>
```
Comment (garyhtou) [inline app/views/events/g_suite_overview.html.erb]:
```suggestion
    <% if !@g_suite.revocation&.revoked? %>
```

**Comment by rluodev** [comment]
- separate mailer
- g suite partial
- mailer preview

**Review by garyhtou — APPROVED** [review]

**Comment by garyhtou** [comment]
TODO:
- Test revocation in prod with one org
- Update immunity for orgs
- Run query to see which orgs (and how many) will enter revocation when the initiate revocation job is run
	- If that looks good, then we enable the cron job.
