### PR TITLE
Fix stripe card defrost policy

### LINKED ISSUE #10682: [Stripe Cards] Improve papertrail
- [ ] determine why so many cards are missing a last frozen by
- [x] make column on DB for last frozen by
- [x] backfill this with the data from papertrail
- [x] fix records that are missing a last frozen by
- [x] ignore cards that are missing a last frozen by / last frozen by is nil in defrost policy

### LINKED ISSUE #10749: [StripeCardPolicy] Ignore cards that don't have a papertrail in defrost

### PR DESCRIPTION
**Pull request by Luke-Oldenburg**
## Summary of the problem

Cards that didn't have a papertrail set were not able to be unfrozen by the cardholder before.
Closes #10682 #10749

## Describe your changes

Check for a presence of a papertrail.

### CODE REVIEW

File: app/policies/stripe_card_policy.rb [hunk 1]
```diff
@@ -14,19 +14,18 @@ def freeze?
...
 
   def defrost?
-    unless record.last_frozen_by == user || admin_or_manager?
-      return false
-    end
+    return false if record&.event&.financially_frozen?
+    return false if record&.last_frozen_by.present? && record&.last_frozen_by != user && !admin_or_manager?
 
-    freeze? && !record.event.financially_frozen?
+    freeze?
```
Comment (sampoder) [inline app/policies/stripe_card_policy.rb]: thank you! a lot cleaner

File: app/policies/stripe_card_policy.rb [hunk 2]
```diff
@@ -68,11 +67,11 @@ def cardholder?
   end
 
   def admin_or_manager?
-    user&.admin? || OrganizerPosition.find_by(user:, event: record.event)&.manager?
+    user&.admin? || OrganizerPosition.find_by(user:, event: record&.event)&.manager?
   end
 
   def grantee?
-    cardholder? && record.card_grant
+    cardholder? && record&.card_grant
```
Comment (sampoder) [inline app/policies/stripe_card_policy.rb]: when would record be `nil`?

Comment (Luke-Oldenburg) [reply app/policies/stripe_card_policy.rb]: It might not be but I saw the & in some places so I standardized it throughout the file.

Comment (sampoder) [reply app/policies/stripe_card_policy.rb]: Can we drop it in all places?

Comment (sampoder) [reply app/policies/stripe_card_policy.rb:74]: Can we drop it in all places?

Comment (Luke-Oldenburg) [reply app/policies/stripe_card_policy.rb]: Sure

**Review by sampoder — APPROVED** [review]
lgtm!
