### PR TITLE
Collect `account_holder` name for Wise reimbursements

### LINKED ISSUE #11682: [Admin] feature name here Wire reimbursements should allow user to enter a name
### Describe the problem

Wire reimbursements are failing because HCB assumes the user's name on HCB is the name of the bank account holder. A field to enter a name should be added. This happens in YSWS mostly because teens are paying out of pocket and then the organizer sends them a reimbursement report to open and fill out.

### Describe the feature/solution (optional)

a field for account owner's name

### PR DESCRIPTION
**Pull request by sampoder**
Closes https://github.com/hackclub/hcb/issues/11682. Not sure how much I like accessing the class inside the concern.

### CODE REVIEW

File: app/models/concerns/has_wise_recipient.rb [hunk 1]
```diff
@@ -24,6 +24,15 @@ module HasWiseRecipient
     def self.information_required_for(currency)
       fields = []
 
+      if self.name.constantize == User::PayoutMethod::WiseTransfer
```
Comment (davidcornu) [inline app/models/concerns/has_wise_recipient.rb]: **question**: Do we need the indirection via `.name.constantize`?

```suggestion
      if self == User::PayoutMethod::WiseTransfer
```

Comment (sampoder) [reply app/models/concerns/has_wise_recipient.rb]: That works! I tried `.is_a?()` first but that didn't work

File: app/views/wise_transfers/_currency_specific_details.html.erb [hunk 2]
```diff
@@ -1,9 +1,9 @@
-<%# locals: (form:, disabled:, excluded_fields: []) %>
+<%# locals: (form:, disabled:, excluded_fields: [], model: User::PayoutMethod::WiseTransfer) %>
```
Comment (davidcornu) [inline app/views/wise_transfers/_currency_specific_details.html.erb]: **concern**: Does this default mean that calls to this partial that don't specific `model` will get the extra field? Do we want that?

Comment (davidcornu) [reply app/views/wise_transfers/_currency_specific_details.html.erb]: e.g. here https://github.com/hackclub/hcb/blob/74a9364f3bbb4b3b0c6685834a092cbb460d082b/app/views/wise_transfers/new.html.erb#L81

Comment (sampoder) [reply app/views/wise_transfers/_currency_specific_details.html.erb]: Oh good catch this should be reversed!
```suggestion
<%# locals: (form:, disabled:, excluded_fields: [], model: WiseTransfer) %>
```

File: app/models/concerns/has_wise_recipient.rb (hunk 1 above)
Comment (davidcornu) [reply app/models/concerns/has_wise_recipient.rb]: > I tried `.is_a?()` first but that didn't work

Yeah `is_a?` works on instances but not on the class objects themselves (which is what we're dealing with in a `def self.*` context).

Comment (sampoder) [reply app/models/concerns/has_wise_recipient.rb]: Interesting - good to know

**Review by davidcornu — APPROVED** [review]
